export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_ADMIN_BEGIN = "SETUP_ADMIN_BEGIN";
export const SETUP_ADMIN_SUCCESS = "SETUP_ADMIN_SUCCESS";
export const SETUP_ADMIN_ERROR = "SETUP_ADMIN_ERROR";

export const UPDATE_ADMIN_BEGIN = "UPDATE_ADMIN_BEGIN";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_ERROR = "UPDATE_ADMIN_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export const ADD_DOCUMENT_BEGIN = "ADD_DOCUMENT_BEGIN";
export const ADD_DOCUMENT_SUCCESS = "ADD_DOCUMENT_SUCCESS";
export const ADD_DOCUMENT_ERROR = "ADD_DOCUMENT_ERROR";

export const GET_DOCS_BEGIN = "GET_DOCS_BEGIN";
export const GET_DOCS_SUCCESS = "GET_DOCS_SUCCESS";

export const DOC_DOWNLOAD_BEGIN = "DOC_DOWNLOAD_BEGIN";
export const DOC_DOWNLOAD_SUCCESS = "DOC_DOWNLOAD_SUCCESS";
export const DOC_DOWNLOAD_ERROR = "DOC_DOWNLOAD_ERROR";

export const SET_EDIT_DOC = "SET_EDIT_DOC";

export const EDIT_DOC_BEGIN = "EDIT_DOC_BEGIN";
export const EDIT_DOC_SUCCESS = "EDIT_DOC_SUCCESS";
export const EDIT_DOC_ERROR = "EDIT_DOC_ERROR";

export const DELETE_DOC_BEGIN = "DELETE_DOC_BEGIN";
