export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_ADMIN_BEGIN = "SETUP_ADMIN_BEGIN";
export const SETUP_ADMIN_SUCCESS = "SETUP_ADMIN_SUCCESS";
export const SETUP_ADMIN_ERROR = "SETUP_ADMIN_ERROR";

export const UPDATE_ADMIN_BEGIN = "UPDATE_ADMIN_BEGIN";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_ERROR = "UPDATE_ADMIN_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export const ADD_DOCUMENT_BEGIN = "ADD_DOCUMENT_BEGIN";
export const ADD_DOCUMENT_SUCCESS = "ADD_DOCUMENT_SUCCESS";
export const ADD_DOCUMENT_ERROR = "ADD_DOCUMENT_ERROR";

export const GET_DOCS_BEGIN = "GET_DOCS_BEGIN";
export const GET_DOCS_SUCCESS = "GET_DOCS_SUCCESS";

export const DOC_DOWNLOAD_BEGIN = "DOC_DOWNLOAD_BEGIN";
export const DOC_DOWNLOAD_SUCCESS = "DOC_DOWNLOAD_SUCCESS";
export const DOC_DOWNLOAD_ERROR = "DOC_DOWNLOAD_ERROR";

export const SET_EDIT_DOC = "SET_EDIT_DOC";

export const EDIT_DOC_BEGIN = "EDIT_DOC_BEGIN";
export const EDIT_DOC_SUCCESS = "EDIT_DOC_SUCCESS";
export const EDIT_DOC_ERROR = "EDIT_DOC_ERROR";

export const DELETE_DOC_BEGIN = "DELETE_DOC_BEGIN";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const GET_STAFF_BEGIN = "GET_STAFF_BEGIN";
export const GET_STAFF_SUCCESS = "GET_STAFF_SUCCESS";

export const SET_EDIT_STAFF = "SET_EDIT_STAFF";

export const EDIT_STAFF_BEGIN = "EDIT_STAFF_BEGIN";
export const EDIT_STAFF_SUCCESS = "EDIT_STAFF_SUCCESS";
export const EDIT_STAFF_ERROR = "EDIT_STAFF_ERROR";

export const DELETE_STAFF_BEGIN = "DELETE_STAFF_BEGIN";

export const GET_PANEL_MEMBER_BEGIN = "GET_PANEL_MEMBER_BEGIN";
export const GET_PANEL_MEMBER_SUCCESS = "GET_PANEL_MEMBER_SUCCESS";

export const GET_USER_PANEL_BEGIN = "GET_USER_PANEL_BEGIN";
export const GET_USER_PANEL_SUCCESS = "GET_USER_PANEL_SUCCESS";

export const SET_EDIT_PANEL_MEMBER = "SET_EDIT_PANEL_MEMBER";

export const EDIT_PANEL_MEMBER_BEGIN = "EDIT_PANEL_MEMBER_BEGIN";
export const EDIT_PANEL_MEMBER_SUCCESS = "EDIT_PANEL_MEMBER_SUCCESS";
export const EDIT_PANEL_MEMBER_ERROR = "EDIT_PANEL_MEMBER_ERROR";

export const GET_STUDENT_BEGIN = "GET_STUDENT_BEGIN";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";

export const SET_EDIT_STUDENT = "SET_EDIT_STUDENT";

export const EDIT_STUDENT_BEGIN = "EDIT_STUDENT_BEGIN";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR";

export const DELETE_STUDENT_BEGIN = "DELETE_STUDENT_BEGIN";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";
