export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const SETUP_ADMIN_BEGIN = "SETUP_ADMIN_BEGIN";
export const SETUP_ADMIN_SUCCESS = "SETUP_ADMIN_SUCCESS";
export const SETUP_ADMIN_ERROR = "SETUP_ADMIN_ERROR";

export const UPDATE_ADMIN_BEGIN = "UPDATE_ADMIN_BEGIN";
export const UPDATE_ADMIN_SUCCESS = "UPDATE_ADMIN_SUCCESS";
export const UPDATE_ADMIN_ERROR = "UPDATE_ADMIN_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";
