export const MARK_LIST_REQUEST = "MARK_LIST_REQUEST";
export const MARK_LIST_SUCCESS = "MARK_LIST_SUCCESS";
export const MARK_LIST_FAIL = "MARK_LIST_FAIL";

export const MARK_CREATE_REQUEST = "MARK_CREATE_REQUEST";
export const MARK_CREATE_SUCCESS = "MARK_CREATE_SUCCESS";
export const MARK_CREATE_FAIL = "MARK_CREATE_FAIL";

export const MARK_UPDATE_REQUEST = "MARK_UPDATE_REQUEST";
export const MARK_UPDATE_SUCCESS = "MARK_UPDATE_SUCCESS";
export const MARK_UPDATE_FAIL = "MARK_UPDATE_FAIL";

export const MARK_DELETE_REQUEST = "MARK_DELETE_REQUEST";
export const MARK_DELETE_SUCCESS = "MARK_DELETE_SUCCESS";
export const MARK_DELETE_FAIL = "MARK_DELETE_FAIL";
