export const TOPIC_LIST_REQUEST = "TOPIC_LIST_REQUEST";
export const TOPIC_LIST_SUCCESS = "TOPIC_LIST_SUCCESS";
export const TOPIC_LIST_FAIL = "TOPIC_LIST_FAIL";


export const TOPIC_UPDATE_REQUEST = "TOPIC_UPDATE_REQUEST";
export const TOPIC_UPDATE_SUCCESS = "TOPIC_UPDATE_SUCCESS";
export const TOPIC_UPDATE_FAIL = "TOPIC_UPDATE_FAIL";