export const SUBMISSION_LIST_REQUEST = "SUBMISSION_LIST_REQUEST";
export const SUBMISSION_LIST_SUCCESS = "SUBMISSION_LIST_SUCCESS";
export const SUBMISSION_LIST_FAIL = "SUBMISSION_LIST_FAIL";

export const SUBMISSION_CREATE_REQUEST = "SUBMISSION_CREATE_REQUEST";
export const SUBMISSION_CREATE_SUCCESS = "SUBMISSION_CREATE_SUCCESS";
export const SUBMISSION_CREATE_FAIL = "SUBMISSION_CREATE_FAIL";

export const SUBMISSION_DELETE_REQUEST = "SUBMISSION_DELETE_REQUEST";
export const SUBMISSION_DELETE_SUCCESS = "SUBMISSION_DELETE_SUCCESS";
export const SUBMISSION_DELETE_FAIL = "SUBMISSION_DELETE_FAIL";